FROM tomcat:latest
MAINTAINER label="anushaaws95@gmail.com"
MAINTAINER "anusha"
LABEL authour="anusha"
LABEL "this is for tomcat practice"
RUN sudo apt update
EXPOSE 8080
ENTRYPOINT ["catalina.sh"]
CMD ["run"]
USER root


