---
 - hosts: all
   become: yes
   tasks:
     - name: install apache service
       apt:
         name: apache2
         update_cache: true
         state: present
     - name: start service
       service:
         name: apache2
         state: started
